from typing import Optional
from pydantic import BaseModel, Field


class EvaluationRequest(BaseModel):
    """
    Model for Evaluation Input Module
    """

    question: str = Field(
        ...,
        title="Question",
        description="User's question to evaluate",
        min_length=1
    )

    response: str = Field(
        ...,
        title="AI Response",
        description="Response generated by the AI model",
        min_length=1
    )

    reference_answer: Optional[str] = Field(
        default=None,
        title="Reference Answer",
        description="Optional reference answer provided by the user"
    )

    source_document: Optional[str] = Field(
        default=None,
        title="Source Document",
        description="Optional source document or context"
    )